# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "dashboard-dre-atual"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5174"
additional_redirect_urls = ["https://bedgpuwdsoliccoaojso.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54321
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions]
enabled = true
verify_jwt = false

[edge_runtime]
enabled = true
port = 54321

# Configuration for remote Supabase project
[remote]
project_ref = "bedgpuwdsoliccoaojso"
api_url = "https://bedgpuwdsoliccoaojso.supabase.co"
db_url = "postgresql://postgres:[YOUR-PASSWORD]@db.bedgpuwdsoliccoaojso.supabase.co:5432/postgres"